[package]
name = "rust_helper"
version = "0.1.0"
authors = ["Jacob Hassold <jhassold@dcscorp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "0.3"

[lib]
crate-type = ["staticlib"]